[tool.ruff]
line-length = 125
ignore = ["D203"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".venv",
]

[tool.ruff.lint]
# allow fix for enabled rules
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
# ignore import errors in __init__.py and test files
"__init__.py" = ["E402", "F403"]
"context.py" = ["E402", "F403", "F401"]
"**/{tests}/*" = ["E402","F405", "F403"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.black]
line-length = 125
target-version = ["py39"]
exclude = ""

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']

[tool.coverage.run]
branch = true

[tool.coverage.html]
directory="coverage_html_report"

[tool.coverage.report]
show_missing=true
