[tool.ruff]
line-length = 125
ignore = ["D203"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"context.py" = ["E402", "F403"]
"*/{tests}/*" = ["E402"]

[tool.black]
line-length = 125
target-version = ["py39"]
exclude = ""

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']

[tool.coverage.run]
branch = true

[tool.coverage.html]
directory="coverage_html_report"

[tool.coverage.report]
show_missing=true
